tab_spaces = 4
use_small_heuristics = "Max"
# brace_style = "PreferSameLine"
# control_brace_style = "AlwaysSameLine"
# fn_single_line = true
# overflow_delimited_expr = true
# where_single_line = true
